
services:
  lb:
    image: haproxy:2.9-alpine
    platform: linux/amd64
    container_name: lb
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.06'
          memory: 14M
    networks:
      - rinha-network

  api1:
    image: maxsonferovante/vector-based-fraud-detection-api:12-05-2026-20-07-55
    platform: linux/amd64
    container_name: api1
    environment:
      - RESOURCES_DIR=resources
    deploy:
      resources:
        limits:
          cpus: '0.47'
          memory: 168M
    networks:
      - rinha-network

  api2:
    image: maxsonferovante/vector-based-fraud-detection-api:12-05-2026-20-07-55
    platform: linux/amd64
    container_name: api2
    environment:
      - RESOURCES_DIR=resources
    deploy:
      resources:
        limits:
          cpus: '0.47'
          memory: 168M
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge
